import Shell from "@/components/Shell";
import Metronome from "@/components/Metronome";
import { supabaseServer } from "@/lib/supabase/server";
export const dynamic = "force-dynamic";
export const metadata = { title: "Drum Academy", description: "A premium percussion learning space from beginner to advanced." };
type L={slug:string;title:string;summary:string|null;level:string;category:string};
const drumTracks=[
 ["Gongo","Traditional Nigerian Drum","Beginner","12 lessons · Foundations, tone and rhythm"],
 ["Talking Drum","Voice of Tradition","Intermediate","10 lessons · Pitch, phrase and call & response"],
 ["Dùndún","Power & Rhythm","All levels","8 lessons · Ensemble roles and musical language"],
 ["Bàtá","Sacred Rhythms","Advanced","10 lessons · Structure, roles and repertoire context"]
];
export default async function Academy(){const {data}=await supabaseServer().from("lessons").select("slug,title,summary,level,category").eq("status","published").order("created_at");const all=(data??[]) as L[]; const featured=all.slice(0,6);
 return <Shell><div className="-mx-4 md:-mx-8"><section className="academy-hero relative overflow-hidden px-5 py-12 md:px-10 md:py-16"><div className="mx-auto max-w-[1450px]"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#f4c968]">SPERART Academy</p><h1 className="mt-3 max-w-4xl text-4xl font-semibold tracking-tight md:text-7xl">Drum Academy.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/65">Learn the language of rhythm. Explore Nigerian drum traditions, technique, reading, ensemble playing and improvisation — from your first strike to advanced practice.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#lessons" className="btn btn-blue">Explore lessons</a><a href="#practice" className="btn btn-line">Open practice room</a></div></div></section>
 <section className="bg-[#f7f4ec] px-5 py-8 md:px-10"><div className="mx-auto max-w-[1450px] flex flex-wrap gap-2">{["All lessons","Gongo","Talking Drum","Dùndún","Bàtá","Beginner","Intermediate","Advanced"].map((x,i)=><span key={x} className={`rounded-full border px-4 py-2 text-xs font-semibold ${i===0?"border-[#d8a63b] bg-[#06142b] text-[#f4c968]":"border-[#e1d5bc] bg-white text-[#06142b]/70"}`}>{x}</span>)}</div></section>
 <section id="lessons" className="px-5 py-14 md:px-10"><div className="mx-auto max-w-[1450px]"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="sperart-kicker">Featured drum lessons</p><h2 className="mt-1 text-3xl font-semibold md:text-4xl">Start where your rhythm is.</h2></div><span className="text-sm text-[#06142b]/50">{all.length} published lessons</span></div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{(featured.length?featured:[]).map(l=><a key={l.slug} href={`/academy/${l.slug}`} className="lesson-card group block p-5"><div className="flex items-center justify-between"><span className="rounded-full bg-[#06142b] px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-[#f4c968]">{l.level}</span><span className="text-[#2e75ff] transition group-hover:translate-x-1">→</span></div><div className="mt-8 grid h-28 place-items-center rounded-2xl bg-[radial-gradient(circle,rgba(216,166,59,.22),transparent_48%),linear-gradient(135deg,#06142b,#0d3b75)]"><span className="text-5xl">🥁</span></div><h3 className="mt-5 text-xl font-semibold text-[#06142b]">{l.title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[#06142b]/55">{l.summary}</p><div className="mt-5 flex items-center justify-between border-t border-[#e7dcc5] pt-4 text-xs"><span className="font-semibold text-[#06142b]/55">{l.category}</span><span className="font-semibold text-[#2e75ff]">Start learning</span></div></a>)}</div></div></section>
 <section className="bg-[#06142b] px-5 py-14 text-white md:px-10"><div className="mx-auto max-w-[1450px]"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#f4c968]">Explore traditions</p><h2 className="mt-2 text-3xl font-semibold md:text-4xl">Choose your drum.</h2><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{drumTracks.map(([name,sub,level,meta])=><article key={name} className="sperart-glass rounded-[26px] p-5"><div className="grid h-32 place-items-center rounded-2xl bg-[radial-gradient(circle,rgba(216,166,59,.2),transparent_45%)] text-6xl">🥁</div><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-[#f4c968]">{level}</p><h3 className="mt-1 text-xl font-semibold">{name}</h3><p className="mt-1 text-sm text-white/55">{sub}</p><p className="mt-4 text-xs text-white/40">{meta}</p><a href="#lessons" className="mt-5 inline-flex text-sm font-semibold text-[#f4c968]">Explore track →</a></article>)}</div></div></section>
 <section id="practice" className="px-5 py-14 md:px-10"><div className="mx-auto grid max-w-[1450px] gap-6 lg:grid-cols-[.8fr_1.2fr]"><div><p className="sperart-kicker">Practice room</p><h2 className="mt-1 text-3xl font-semibold">Build the habit.</h2><p className="mt-3 max-w-lg leading-7 text-[#06142b]/55">Slow practice, steady pulse and deliberate repetition. Use the metronome alongside every lesson.</p></div><Metronome/></div></section>
 </div></Shell>;
}
