import Shell from "@/components/Shell";
import Metronome from "@/components/Metronome";
import { supabaseServer } from "@/lib/supabase/server";
export const dynamic = "force-dynamic";
export const metadata = { title: "Drum Academy", description: "Learn Nigerian and world percussion through structured lessons, practice and rhythm." };
type L = { slug: string; title: string; summary: string | null; level: string; category: string };
const tracks = [
  { key: "Gongo", title: "Gongo", sub: "Traditional Nigerian Drum", level: "Beginner", tone: "from-[#7a4b1d] via-[#d59a45] to-[#06122E]" },
  { key: "Talking Drum", title: "Talking Drum", sub: "Voice of Tradition", level: "Intermediate", tone: "from-[#7b3b25] via-[#d88949] to-[#06122E]" },
  { key: "Dundun", title: "Dùndún", sub: "Power & Rhythm", level: "All Levels", tone: "from-[#5b351e] via-[#c47b39] to-[#06122E]" },
  { key: "Bata", title: "Bàtá", sub: "Sacred Rhythms", level: "Advanced", tone: "from-[#4f241b] via-[#b9693e] to-[#06122E]" },
];
export default async function Academy() {
  const { data } = await supabaseServer().from("lessons").select("slug,title,summary,level,category").eq("status", "published").order("created_at");
  const all = (data ?? []) as L[];
  return <Shell>
    <section className="academy-hero relative overflow-hidden rounded-[36px] bg-[#06122E] p-7 text-white shadow-[0_30px_90px_rgba(6,18,46,.25)] md:p-12">
      <div className="academy-orb academy-orb-one"/><div className="academy-orb academy-orb-two"/>
      <div className="relative max-w-3xl"><p className="eyebrow text-gold">SPERART DRUM ACADEMY</p><h1 className="mt-3 text-5xl font-semibold tracking-tight md:text-7xl">Learn. Practice. Master.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">Explore structured lessons on Nigerian drums, traditional rhythms and modern percussion technique. Learn at your level, practise with purpose and grow with SPERART.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#lessons" className="btn btn-gold">Explore lessons</a><a href="#practice" className="btn btn-glass">Practice with metronome</a></div></div>
      <div className="academy-drum-mark" aria-hidden><img src="/emblem.png" alt=""/></div>
    </section>
    <section className="mt-7 flex flex-wrap gap-2 rounded-[24px] border border-blue/10 bg-white p-3 shadow-sm"><a href="#lessons" className="filter-pill active">All Lessons</a>{tracks.map(t=><a key={t.key} href={`#${t.key.toLowerCase().replace(/\s/g,"-")}`} className="filter-pill">{t.title}</a>)}<a href="#lessons" className="filter-pill">Other Drums</a></section>
    <section id="lessons" className="mt-12"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow text-blue">Featured drum lessons</p><h2 className="mt-2 text-3xl font-semibold md:text-4xl">Find your rhythm</h2></div><a href="#curriculum" className="text-sm font-semibold text-blue">View curriculum →</a></div>
      <div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{tracks.map((t,i)=>{const lesson=all.find(l=>l.category?.toLowerCase().includes(t.key.toLowerCase())||l.title?.toLowerCase().includes(t.key.toLowerCase())); return <article id={t.key.toLowerCase().replace(/\s/g,"-")} key={t.key} className="drum-card group overflow-hidden"><div className={`drum-card-art bg-gradient-to-br ${t.tone}`}><div className="drum-illustration"><span/><span/><span/></div><div className="absolute left-4 top-4 rounded-full border border-white/20 bg-black/20 px-2.5 py-1 text-[11px] font-semibold text-white backdrop-blur">{t.level}</div></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue">{t.sub}</p><h3 className="mt-1 text-xl font-semibold">{t.title}</h3><p className="mt-2 text-sm leading-6 text-ink/60">{lesson?.summary ?? `Build a strong foundation in ${t.title.toLowerCase()} technique, listening, rhythm and musical expression.`}</p><p className="mt-3 text-xs text-ink/45">{lesson ? "Published lesson" : "Curated learning track"}</p><a href={lesson ? `/academy/${lesson.slug}` : "/academy"} className="btn btn-gold mt-5 w-full !py-3">Start learning</a></div></article>})}</div>
    </section>
    <section id="curriculum" className="mt-14 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[30px] border border-blue/10 bg-white p-6 shadow-sm md:p-8"><p className="eyebrow text-blue">Complete curriculum</p><h2 className="mt-2 text-3xl font-semibold">From first strike to confident performance.</h2><p className="mt-3 max-w-2xl leading-7 text-ink/60">Beginner, intermediate and advanced pathways cover technique, rhythm reading, call-and-response, ensemble playing, improvisation and Nigerian drum traditions.</p><div className="mt-7 space-y-3">{["Beginner — foundations, tone, timing and basic patterns","Intermediate — syncopation, accompaniment and phrase building","Advanced — ensemble leadership, improvisation and arrangement"].map((x,i)=><div key={x} className="flex gap-3 rounded-2xl bg-bone p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-gold text-navy font-bold">{i+1}</span><p className="text-sm font-medium leading-6">{x}</p></div>)}</div></div><div id="practice" className="rounded-[30px] bg-[linear-gradient(135deg,#06122E,#0d2d68)] p-6 text-white shadow-[0_22px_70px_rgba(6,18,46,.2)] md:p-8"><p className="eyebrow text-gold">Practice room</p><h2 className="mt-2 text-3xl font-semibold">Train your timing.</h2><p className="mt-3 text-white/60">Set a tempo, repeat a pattern and make practice part of your routine.</p><div className="mt-6"><Metronome /></div></div></section>
    <section className="mt-14 rounded-[30px] border border-gold/30 bg-[radial-gradient(circle_at_90%_10%,rgba(255,201,60,.2),transparent_30%),#fffaf0] p-7 md:p-10"><p className="eyebrow text-blue">SPERART AI</p><div className="mt-2 flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><h2 className="text-3xl font-semibold">Need a lesson? Ask your AI.</h2><p className="mt-2 max-w-2xl text-ink/60">Ask for a beginner talking-drum lesson, a weekly practice plan, rhythm-reading help or the next step in your course.</p></div><a href="/account" className="btn btn-blue shrink-0">Open SPERART AI</a></div></section>
  </Shell>;
}
