type Field = [name: string, label: string, kind?: string];
/** Admin-managed record types. Add a new entry to get a new editor at /admin/manage/<key>. */
export const kinds: Record<string, { table: string; label: string; fields: Field[] }> = {
  news: { table: "articles", label: "News", fields: [["title", "Title"], ["excerpt", "Short summary", "area"], ["cover_url", "Cover image link (copy from Media)"], ["body", "Article text", "area-lg"], ["status", "Status", "status"]] },
  lessons: { table: "lessons", label: "Academy", fields: [["title", "Title"], ["category", "Type", "opts:Lesson,Rudiment"], ["level", "Level", "opts:Beginner,Intermediate,Advanced"], ["summary", "Short summary", "area"], ["video_url", "Video link (copy from Media)"], ["audio_url", "Audio link (copy from Media)"], ["body", "Lesson text and instructions", "area-lg"], ["status", "Status", "status"]] },
  recognition: { table: "recognitions", label: "Recognition", fields: [["title", "Title or name"], ["category", "Type", "opts:Award,Scholarship,Honour,Competition,Featured Artist"], ["year", "Year (e.g. 2026)"], ["summary", "Description", "area"], ["image_url", "Image link (copy from Media)"], ["status", "Status", "status"]] },
  library: { table: "resources", label: "Library", fields: [["title", "Title"], ["category", "Type", "opts:Article,Research,Publication,Educational resource,Archive"], ["tags", "Tags (comma separated)"], ["summary", "Summary", "area"], ["url", "Link to the file or page (copy from Media, or paste a web address)"], ["status", "Status", "status"]] },
  events: { table: "events", label: "Events", fields: [["title", "Title"], ["starts_at", "Date and time (Lagos time)", "datetime"], ["capacity", "Seats available (leave empty for unlimited)", "number"], ["location", "Location"], ["cover_url", "Cover image link (copy from Media)"], ["description", "Description", "area-lg"], ["status", "Status", "status"]] },
};
