import { redirect } from "next/navigation";
import { supabaseServer } from "@/lib/supabase/server";
import ThemeToggle from "@/components/ThemeToggle";
import { signOut } from "./actions";
const nav = [["Overview", "/admin", "⌂"], ["AI Assistant", "/admin/assistant", "✦"], ["Messages", "/admin/inbox", "◌"], ["Edit content", "/admin/content", "▣"], ["Media", "/admin/media", "◈"], ["News", "/admin/manage/news", "✎"], ["Events", "/admin/manage/events", "◷"], ["Academy", "/admin/manage/lessons", "♫"], ["Recognition", "/admin/manage/recognition", "★"], ["Library", "/admin/manage/library", "▤"], ["Registrations", "/admin/registrations", "✓"], ["Members", "/admin/members", "♙"], ["Subscribers", "/admin/subscribers", "@"]];
export default async function AdminLayout({ children }: { children: React.ReactNode }) {
 const sb=supabaseServer(); const {data:{user}}=await sb.auth.getUser(); if(!user) redirect("/login"); const {data:admin}=await sb.from("admins").select("user_id").eq("user_id",user.id).maybeSingle(); if(!admin) redirect("/");
 return <div className="admin-shell min-h-screen md:flex"><aside className="admin-sidebar"><div className="flex items-center justify-between px-5 py-5"><a href="/" className="flex items-center gap-3"><span className="admin-logo"><img src="/emblem.png" alt="SPERART"/></span><span><strong className="block tracking-[.18em] text-white">SPERART</strong><small className="text-[10px] uppercase tracking-[.18em] text-white/40">Command Centre</small></span></a><div className="md:hidden"><ThemeToggle/></div></div><nav className="space-y-1 px-3 pb-4">{nav.map(([t,h,i])=><a key={h} href={h} className="admin-nav"><span className="admin-nav-icon">{i}</span><span>{t}</span></a>)}</nav><div className="mt-auto hidden items-center justify-between border-t border-white/10 p-4 md:flex"><ThemeToggle/><form action={signOut}><button className="text-xs text-white/50 hover:text-white">Sign out</button></form></div><form action={signOut} className="px-5 pb-5 md:hidden"><button className="text-sm text-white/60">Sign out</button></form></aside><main className="admin-main mx-auto w-full flex-1 p-4 md:p-8 lg:p-10">{children}</main></div>;
}
