import { supabaseServer } from "@/lib/supabase/server";
import SperartMark from "@/components/SperartMark";
export const dynamic = "force-dynamic";
async function count(table: string, status?: string) { let q=supabaseServer().from(table).select("*",{count:"exact",head:true}); if(status) q=q.eq("status",status); return (await q).count??0; }
const quick=[ ["Members","/admin/members","Review approvals","01"],["Messages","/admin/inbox","Reply to members","02"],["Content","/admin/content","Shape the site","03"],["Academy","/admin/manage/lessons","Build learning","04"],["Events","/admin/manage/events","Publish experiences","05"],["Media","/admin/media","Manage your library","06"] ];
export default async function AdminHome(){
 const [msgs,pending,regs,subs,news,drafts,media]=await Promise.all([count("inquiries","new"),count("profiles","pending"),count("registrations"),count("subscribers"),count("articles","published"),count("articles","draft"),count("media")]);
 const {data:recent}=await supabaseServer().from("inquiries").select("id,name,message,status,created_at").order("created_at",{ascending:false}).limit(4);
 const attention=[pending?`${pending} member${pending>1?"s":""} waiting for approval`:"No member approvals waiting",msgs?`${msgs} new message${msgs>1?"s":""} need attention`:"Inbox is clear",drafts?`${drafts} draft article${drafts>1?"s":""} in your workspace`:"No article drafts waiting"];
 const stats=[["Total members",await count("profiles"),"/admin/members","Members"],["Pending approvals",pending,"/admin/members","Review"],["New messages",msgs,"/admin/inbox","Inbox"],["Published news",news,"/admin/manage/news","Live"],["Registrations",regs,"/admin/registrations","Activity"],["Media assets",media,"/admin/media","Library"]];
 const hour=Number(new Date().toLocaleString("en-GB",{hour:"2-digit",hour12:false,timeZone:"Africa/Lagos"})); const greet=hour<12?"Good morning":hour<17?"Good afternoon":"Good evening";
 return <div className="sperart-dashboard -m-4 min-h-[calc(100vh-2rem)] p-4 md:-m-8 md:p-8">
  <div className="mx-auto max-w-[1500px] space-y-6">
   <section className="sperart-hero-grid relative overflow-hidden rounded-[34px] p-6 shadow-[0_30px_100px_rgba(6,20,43,.22)] md:p-9">
    <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full border border-white/10"/><div className="absolute right-16 bottom-0 h-40 w-40 rounded-full bg-[#D8A63B]/10 blur-3xl"/>
    <div className="relative flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between">
      <div><SperartMark/><p className="sperart-kicker mt-8 !text-[#f4c968]">Command centre</p><h1 className="mt-2 text-4xl font-semibold tracking-tight text-white md:text-6xl">{greet}, Admin.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-white/65">Your organisation at a glance. See what matters, move quickly, and let SPERART AI handle the routine work.</p></div>
      <a href="/admin/assistant" className="sperart-glass group flex items-center gap-4 rounded-3xl p-4 transition hover:-translate-y-1"><span className="grid h-14 w-14 overflow-hidden rounded-2xl border border-[#f4c968]/50 bg-[#06142b]"><img src="/emblem.png" alt="SPERART AI" className="h-full w-full object-cover"/></span><span><strong className="block text-white">SPERART AI</strong><small className="mt-1 block text-white/55">Your digital operator · Open AI →</small></span></a>
    </div>
   </section>
   <section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{stats.map(([k,v,h,l])=><a key={String(h)} href={String(h)} className="sperart-stat group p-4 transition hover:-translate-y-1"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#06142b] text-xs font-bold text-[#f4c968]">{String(l).slice(0,2)}</span><span className="text-xs text-[#2e75ff]">↗</span></div><strong className="mt-5 block text-2xl text-[#06142b]">{String(v)}</strong><p className="mt-1 text-xs text-[#06142b]/55">{String(k)}</p></a>)}</section>
   <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
    <section className="rounded-[30px] border border-[#e7dcc5] bg-[#fffdf8] p-6 shadow-[0_18px_70px_rgba(6,20,43,.07)] md:p-7"><div className="flex items-start justify-between"><div><p className="sperart-kicker">AI attention</p><h2 className="mt-1 text-2xl font-semibold text-[#06142b]">What needs your attention?</h2><p className="mt-1 text-sm text-[#06142b]/55">The important things, without the noise.</p></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#06142b] text-[#f4c968]">AI</span></div><div className="mt-6 space-y-3">{attention.map((x,i)=><div key={i} className="flex items-center gap-4 rounded-2xl border border-[#e7dcc5] bg-[#f7f4ec] p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#d8a63b] font-bold text-[#06142b]">{x.startsWith("No")?"✓":"!"}</span><p className="text-sm font-medium text-[#06142b]">{x}</p><span className="ml-auto text-xs text-[#2e75ff]">View →</span></div>)}</div><a href="/admin/assistant" className="btn btn-blue mt-5">Open SPERART AI</a></section>
    <section className="sperart-dark-panel rounded-[30px] p-6 shadow-[0_22px_70px_rgba(6,20,43,.2)] md:p-7"><p className="sperart-kicker !text-[#f4c968]">Quick actions</p><h2 className="mt-1 text-2xl font-semibold">Run the organisation.</h2><div className="mt-5 grid grid-cols-2 gap-3">{quick.map(([t,h,s,n])=><a key={h} href={h} className="sperart-glass rounded-2xl p-4 transition hover:-translate-y-1 hover:bg-white/15"><span className="text-[10px] font-bold tracking-[.2em] text-[#f4c968]">{n}</span><strong className="mt-3 block text-sm">{t}</strong><span className="mt-1 block text-xs text-white/45">{s}</span></a>)}</div></section>
   </div>
   <section className="rounded-[30px] border border-[#e7dcc5] bg-[#fffdf8] p-6 shadow-[0_18px_70px_rgba(6,20,43,.06)] md:p-7"><div className="flex items-end justify-between"><div><p className="sperart-kicker">Inbox pulse</p><h2 className="mt-1 text-2xl font-semibold text-[#06142b]">Latest messages</h2></div><a href="/admin/inbox" className="text-sm font-semibold text-[#2e75ff]">Open inbox →</a></div><div className="mt-5 grid gap-3 md:grid-cols-2">{recent?.map(m=><a key={m.id} href="/admin/inbox" className="rounded-2xl border border-[#e7dcc5] bg-[#f7f4ec] p-5 transition hover:-translate-y-1 hover:border-[#d8a63b]"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-[#06142b]">{m.name}</p><span className="text-xs text-[#06142b]/40">{new Date(m.created_at).toLocaleDateString("en-NG")}</span></div><p className="mt-2 truncate text-sm text-[#06142b]/55">{m.message}</p></a>)}{!recent?.length&&<p className="text-sm text-[#06142b]/50">Your inbox is clear.</p>}</div></section>
  </div></div>;
}
