"use client";
import { useEffect, useRef, useState } from "react";
import { runActions, type Action } from "@/app/admin/agent";
import { supabaseBrowser } from "@/lib/supabase/browser";
type M={role:"user"|"assistant";content:string;pending?:Action[];results?:string[]};
const ideas=["What needs my attention?","Create a polished percussion workshop announcement","Create a beginner djembe lesson","Approve all pending members"];
const label=(a:Action)=>`${a.type.replace(/_/g," ")}${a.args?.title?`: ${a.args.title}`:a.args?.email?`: ${a.args.email}`:""}`;
export default function AdminAssistant(){
 const [msgs,setMsgs]=useState<M[]>([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[full,setFull]=useState(true); const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{const saved=localStorage.getItem("sp-ai-full");setFull(saved===null||saved==="1")},[]); useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth",block:"end"})},[msgs,busy]);
 const toggle=()=>{const v=!full;setFull(v);localStorage.setItem("sp-ai-full",v?"1":"0")};
 async function send(t:string){if(!t.trim()||busy)return;const next=[...msgs,{role:"user" as const,content:t.trim()}];setMsgs(next);setText("");setBusy(true);try{const r=await fetch("/api/admin/assistant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:next.map(m=>({role:m.role,content:m.content}))})});const j=await r.json();const acts:Action[]=Array.isArray(j.actions)?j.actions:[];const safe=full?acts.filter(a=>a.type!=="delete_item"):[];const pending=acts.filter(a=>!safe.includes(a));const results=safe.length?await runActions(safe,true):undefined;setMsgs([...next,{role:"assistant",content:j.reply??j.error??"I’m ready.",pending:pending.length?pending:undefined,results}])}catch{setMsgs([...next,{role:"assistant",content:"I couldn’t reach the AI service. The rest of your admin dashboard is still available."}])}setBusy(false)}
 async function decide(i:number,approve:boolean){const m=msgs[i];if(!m.pending)return;const results=approve?await runActions(m.pending,false):["Nothing was changed."];setMsgs(all=>all.map((x,n)=>n===i?{...x,pending:undefined,results:[...(x.results??[]),...results]}:x))}
 async function attach(e:React.ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]);if(!files.length)return;const sb=supabaseBrowser(),names:string[]=[];for(const f of files){const kind=f.type.startsWith("video")?"video":f.type.startsWith("audio")?"audio":f.type.startsWith("image")?"image":"document";const path=`${kind}/${Date.now()}-${f.name.replace(/[^\w.-]/g,"_")}`;const {error}=await sb.storage.from("media").upload(path,f);if(!error){await sb.from("media").insert({kind,bucket:"media",path,title:f.name});names.push(`${kind} "${f.name}"`)}}e.target.value="";if(names.length)send(`I uploaded ${names.join(", ")}. Use your judgement about the best place for them.`)}
 return <div className="mt-6 overflow-hidden rounded-[30px] border border-blue/10 bg-white shadow-[0_24px_80px_rgba(15,82,255,.1)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-blue/10 bg-bone/50 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 overflow-hidden rounded-2xl border border-gold/40 bg-navy shadow-[0_0_22px_rgba(15,82,255,.35)]"><img src="/emblem.png" alt="SPERART" className="h-full w-full object-cover" /></span><div><p className="font-semibold">SPERART AI</p><p className="text-xs text-ink/50">{full?"Full control · safe actions run automatically":"Ask first"}</p></div></div><button onClick={toggle} role="switch" aria-checked={full} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${full?"bg-blue text-white":"border border-blue/20"}`}>{full?"FULL CONTROL ON":"ASK FIRST"}</button></div>
 <div className="min-h-[30rem] space-y-4 overflow-y-auto bg-[radial-gradient(circle_at_90%_0%,rgba(76,141,255,.09),transparent_28%)] p-5">{!msgs.length&&<div className="rounded-[24px] border border-blue/10 bg-white p-5"><p className="text-lg font-semibold">Tell me what you need. I’ll work it out.</p><p className="mt-2 max-w-2xl text-sm leading-6 text-ink/60">You don’t need to give me database fields, IDs or technical instructions. I can use the SPERART context, make sensible content decisions and carry out safe tasks. Deletions remain the only confirmation-gated operation.</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{ideas.map(i=><button key={i} onClick={()=>send(i)} className="rounded-2xl border border-blue/10 bg-bone/50 p-3 text-left text-sm font-medium transition hover:-translate-y-0.5 hover:border-blue/30 hover:bg-white">{i}<span className="ml-2 text-blue">→</span></button>)}</div></div>}
 {msgs.map((m,i)=><div key={i} className={m.role==="user"?"flex justify-end":"flex justify-start"}><div className={`max-w-[90%] rounded-[22px] px-4 py-3 ${m.role==="user"?"bg-blue text-white":"border border-blue/10 bg-white shadow-sm"}`}><p className="whitespace-pre-wrap text-sm leading-6">{m.content}</p>{m.results?.map((r,n)=><p key={n} className="mt-2 rounded-xl bg-green-50 px-3 py-2 text-sm text-green-800">✓ {r}</p>)}{m.pending&&<div className="mt-3 rounded-xl border border-gold bg-bone p-3 text-sm"><p className="font-semibold">Confirmation required</p><p className="mt-1 text-ink/60">{m.pending.map(label).join(" · ")}</p><div className="mt-3 flex gap-2"><button onClick={()=>decide(i,true)} className="btn btn-blue !px-4 !py-2">Confirm</button><button onClick={()=>decide(i,false)} className="btn border border-gold !px-4 !py-2">Cancel</button></div></div>}</div></div>)}{busy&&<div className="flex items-center gap-2 text-sm text-ink/50"><span className="grid h-7 w-7 overflow-hidden rounded-full border border-gold/40 bg-navy"><img src="/emblem.png" alt="SPERART" className="h-full w-full object-cover" /></span> Thinking through SPERART…</div>}<div ref={end}/></div>
 <div className="border-t border-blue/10 p-3"><div className="flex items-center gap-2"><label className="grid h-11 w-11 shrink-0 cursor-pointer place-items-center rounded-xl border border-blue/10 bg-bone font-semibold">＋<input type="file" multiple hidden onChange={attach} accept="image/*,video/*,audio/*,.pdf"/></label><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send(text)} placeholder="Tell your AI what you want…" className="field"/><button onClick={()=>send(text)} className="btn btn-blue !px-5">Send</button></div></div></div>
}
