import { redirect } from "next/navigation";
import Shell from "@/components/Shell";
import AccountNotifications from "@/components/AccountNotifications";
import MemberAI from "@/components/MemberAI";
import SperartMark from "@/components/SperartMark";
import { supabaseServer } from "@/lib/supabase/server";
import { getSettings, lines, cols } from "@/lib/settings";
import { saveProfile, sendMemberMessage } from "./actions";
import { signOut } from "../admin/actions";
export const dynamic = "force-dynamic";
export const metadata = { title: "Member dashboard" };
const labels: Record<string,string> = { pending:"Pending approval", active:"Active member", inactive:"Inactive member" };
export default async function Account({ searchParams }: { searchParams: { saved?: string; message?: string } }) {
 const sb=supabaseServer(); const {data:{user}}=await sb.auth.getUser(); if(!user)redirect("/login");
 const [{data:p},{data:adm},{data:notifications},{data:messages},settings]=await Promise.all([sb.from("profiles").select("*").eq("user_id",user.id).maybeSingle(),sb.from("admins").select("user_id").eq("user_id",user.id).maybeSingle(),sb.from("notifications").select("id,title,body,type,link,created_at,read_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(30),sb.from("member_messages").select("id,sender_id,recipient_id,body,created_at,read_at").or(`sender_id.eq.${user.id},recipient_id.eq.${user.id}`).order("created_at",{ascending:true}).limit(30),getSettings()]);
 const types=lines(settings.membership.tiers).map(l=>cols(l)[0]); const unread=(notifications??[]).filter(n=>!n.read_at).length; const status=p?.status??"pending"; const first=p?.full_name?.split(" ")[0]||"member";
 return <Shell><div className="sperart-dashboard -mx-4 min-h-[calc(100vh-5rem)] px-4 py-2 md:-mx-8 md:px-8 md:py-5"><div className="mx-auto max-w-[1450px] space-y-6">
  <section className="sperart-hero-grid relative overflow-hidden rounded-[34px] p-6 text-white shadow-[0_30px_100px_rgba(6,20,43,.2)] md:p-9"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_70%_25%,rgba(216,166,59,.25),transparent_28%)]"/><div className="relative flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><div><SperartMark/><p className="mt-8 text-xs font-bold uppercase tracking-[.28em] text-[#f4c968]">Member space</p><h1 className="mt-2 text-4xl font-semibold tracking-tight md:text-6xl">Welcome back, {first}.</h1><p className="mt-3 max-w-2xl text-white/65">Your culture. Your rhythm. Your journey — with your learning, events, messages and SPERART AI in one place.</p></div><div className="flex items-center gap-3"><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm">{labels[status]||status}</span>{adm&&<a href="/admin" className="btn border border-white/20 !px-4 !py-2 text-sm text-white">Command Centre</a>}</div></div><div className="relative mt-8 grid gap-3 sm:grid-cols-4"><div className="sperart-glass rounded-2xl p-4"><p className="text-xs text-white/45">Membership</p><p className="mt-1 font-semibold">{p?.membership_type||"Member"}</p></div><div className="sperart-glass rounded-2xl p-4"><p className="text-xs text-white/45">Notifications</p><p className="mt-1 font-semibold">{unread?`${unread} unread`:"All caught up"}</p></div><div className="sperart-glass rounded-2xl p-4"><p className="text-xs text-white/45">Messages</p><p className="mt-1 font-semibold">{messages?.length||0} in conversation</p></div><a href="/academy" className="sperart-glass rounded-2xl p-4 transition hover:bg-white/15"><p className="text-xs text-white/45">Academy</p><p className="mt-1 font-semibold">Continue learning →</p></a></div></section>
  <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="space-y-6"><section><div className="mb-3"><p className="sperart-kicker">Your member centre</p><h2 className="text-2xl font-semibold">Stay connected.</h2></div><AccountNotifications items={notifications??[]}/></section><MemberAI/></div><div className="space-y-6"><section className="card !rounded-[28px]"><div className="flex items-center justify-between"><div><p className="sperart-kicker">Profile</p><h2 className="mt-1 text-xl font-semibold">Your details</h2></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#06142b] text-[#f4c968]">✦</span></div><form action={saveProfile} className="mt-5 space-y-4"><label className="block text-sm">Full name<input name="full_name" defaultValue={p?.full_name??""} className="field mt-1"/></label><label className="block text-sm">Phone<input name="phone" defaultValue={p?.phone??""} className="field mt-1"/></label><label className="block text-sm">Membership type<select name="membership_type" defaultValue={p?.membership_type??""} className="field mt-1"><option value="">Choose one</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><button className="btn btn-blue w-full">Save changes</button>{searchParams.saved==="1"&&<p className="text-sm text-green-700">Profile updated successfully.</p>}</form></section>
  <section className="card !rounded-[28px]"><p className="sperart-kicker">Talk to SPERART</p><h2 className="mt-1 text-xl font-semibold">Message the team</h2><p className="mt-2 text-sm leading-6 text-ink/60">Ask about membership, events, Academy or anything you need.</p><form action={sendMemberMessage} className="mt-4 space-y-3"><textarea name="body" className="field min-h-32 resize-y" placeholder="Write your message…"/><button className="btn btn-blue w-full">Send message</button>{searchParams.message==="sent"&&<p className="text-sm text-green-700">Message sent to the SPERART team.</p>}</form></section>
  <section className="card !rounded-[28px]"><p className="sperart-kicker">Conversation</p><h2 className="mt-1 text-xl font-semibold">Your messages</h2><div className="mt-4 max-h-72 space-y-2 overflow-y-auto">{!messages?.length?<p className="text-sm text-ink/50">Your conversations with SPERART will appear here.</p>:messages.map(m=><div key={m.id} className={`rounded-2xl p-3 text-sm ${m.sender_id===user.id?"ml-6 bg-[#0d3b75] text-white":"mr-6 bg-[#f7f4ec]"}`}><p className="leading-6">{m.body}</p><p className="mt-1 text-[11px] opacity-50">{new Date(m.created_at).toLocaleString("en-NG")}</p></div>)}</div></section><form action={signOut}><button className="w-full rounded-full border border-red-200 px-4 py-3 text-sm text-red-600 hover:bg-red-50">Sign out</button></form></div></div>
 </div></div></Shell>;
}
